import { userService } from '../services/userService';
import { driverService } from '../services/driverService';
import { vehicleService } from '../services/vehicleService';
import { tripService } from '../services/tripService';
import { maintenanceService } from '../services/maintenanceService';
import { fuelService } from '../services/fuelService';
import { expenseService } from '../services/expenseService';
import { users, drivers, vehicles, trips, maintenanceRequests, fuelLogs, expenses } from '../data/mockData';

export const managementConfigs = {
  users: {
    title: 'Users',
    description: 'Manage platform users, roles, and user lifecycle actions.',
    service: userService,
    createLabel: 'Add User',
    searchPlaceholder: 'Search users by name, email, or role...',
    searchableKeys: ['fullName', 'email', 'roleName', 'employeeCode'],
    summaryCards: [
      { title: 'Total Users', value: users.length, helper: 'Active platform accounts' },
      { title: 'Admins', value: 1, helper: 'Elevated access' },
      { title: 'Drivers', value: 1, helper: 'Operational users' },
      { title: 'Inactive', value: 0, helper: 'Hidden accounts' },
    ],
    columns: [
      { key: 'employeeCode', label: 'Employee Code' },
      { key: 'fullName', label: 'Full Name' },
      { key: 'email', label: 'Email' },
      { key: 'roleName', label: 'Role' },
      { key: 'employmentStatus', label: 'Status' },
    ],
    fields: [
      { name: 'employeeCode', label: 'Employee Code' },
      { name: 'fullName', label: 'Full Name' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'phone', label: 'Phone' },
      { name: 'roleName', label: 'Role', type: 'select', options: [
        { label: 'Admin', value: 'Admin' },
        { label: 'Fleet Manager', value: 'Fleet Manager' },
        { label: 'Driver', value: 'Driver' },
        { label: 'Safety Officer', value: 'Safety Officer' },
        { label: 'Financial Analyst', value: 'Financial Analyst' },
      ] },
      { name: 'employmentStatus', label: 'Employment Status', type: 'select', options: [
        { label: 'Active', value: 'ACTIVE' },
        { label: 'Inactive', value: 'INACTIVE' },
        { label: 'Suspended', value: 'SUSPENDED' },
        { label: 'Resigned', value: 'RESIGNED' },
      ] },
    ],
  },
  drivers: {
    title: 'Drivers',
    description: 'Maintain driver profiles, license data, and safety performance.',
    service: driverService,
    createLabel: 'Add Driver',
    searchPlaceholder: 'Search drivers by name or license...',
    searchableKeys: ['fullName', 'licenseNumber', 'driverStatus'],
    summaryCards: [
      { title: 'Total Drivers', value: drivers.length, helper: 'Linked to user accounts' },
      { title: 'Available', value: 1, helper: 'Ready for assignment' },
      { title: 'On Trip', value: 1, helper: 'Currently driving' },
      { title: 'Safety Avg', value: '95%', helper: 'Fleet safety score' },
    ],
    columns: [
      { key: 'fullName', label: 'Driver' },
      { key: 'licenseNumber', label: 'License Number' },
      { key: 'licenseCategory', label: 'Category' },
      { key: 'licenseExpiry', label: 'Expiry' },
      { key: 'safetyScore', label: 'Safety Score' },
      { key: 'driverStatus', label: 'Status' },
    ],
    fields: [
      { name: 'fullName', label: 'Driver Name' },
      { name: 'licenseNumber', label: 'License Number' },
      { name: 'licenseCategory', label: 'License Category', type: 'select', options: [
        { label: 'LMV', value: 'LMV' },
        { label: 'HMV', value: 'HMV' },
        { label: 'MCWG', value: 'MCWG' },
        { label: 'HPMV', value: 'HPMV' },
        { label: 'TRANS', value: 'TRANS' },
      ] },
      { name: 'licenseExpiry', label: 'License Expiry', type: 'date' },
      { name: 'safetyScore', label: 'Safety Score', type: 'number' },
      { name: 'driverStatus', label: 'Driver Status', type: 'select', options: [
        { label: 'Available', value: 'AVAILABLE' },
        { label: 'On Trip', value: 'ON_TRIP' },
        { label: 'Off Duty', value: 'OFF_DUTY' },
        { label: 'Suspended', value: 'SUSPENDED' },
      ] },
    ],
  },
  vehicles: {
    title: 'Vehicles',
    description: 'Track fleet assets, status, and vehicle master data.',
    service: vehicleService,
    createLabel: 'Add Vehicle',
    searchPlaceholder: 'Search vehicles by code, reg number, or model...',
    searchableKeys: ['vehicleCode', 'registrationNumber', 'manufacturer', 'model', 'vehicleStatus'],
    summaryCards: [
      { title: 'Total Vehicles', value: vehicles.length, helper: 'Fleet asset count' },
      { title: 'Available', value: 1, helper: 'Ready to deploy' },
      { title: 'On Trip', value: 1, helper: 'In operation' },
      { title: 'Maintenance', value: 1, helper: 'Needs service' },
    ],
    columns: [
      { key: 'vehicleCode', label: 'Vehicle Code' },
      { key: 'registrationNumber', label: 'Registration Number' },
      { key: 'vehicleType', label: 'Vehicle Type' },
      { key: 'manufacturer', label: 'Manufacturer' },
      { key: 'model', label: 'Model' },
      { key: 'manufacturingYear', label: 'Year' },
      { key: 'capacity', label: 'Capacity' },
      { key: 'vehicleStatus', label: 'Status' },
    ],
    fields: [
      { name: 'vehicleCode', label: 'Vehicle Code' },
      { name: 'registrationNumber', label: 'Registration Number' },
      { name: 'vehicleType', label: 'Vehicle Type', type: 'select', options: [
        { label: 'Truck', value: 'Truck' },
        { label: 'Van', value: 'Van' },
        { label: 'Bus', value: 'Bus' },
        { label: 'Bike', value: 'Bike' },
        { label: 'Car', value: 'Car' },
      ] },
      { name: 'manufacturer', label: 'Manufacturer' },
      { name: 'model', label: 'Model' },
      { name: 'manufacturingYear', label: 'Year', type: 'number' },
      { name: 'capacity', label: 'Capacity' },
      { name: 'vehicleStatus', label: 'Status', type: 'select', options: [
        { label: 'Available', value: 'AVAILABLE' },
        { label: 'On Trip', value: 'ON_TRIP' },
        { label: 'In Maintenance', value: 'IN_MAINTENANCE' },
        { label: 'Retired', value: 'RETIRED' },
      ] },
    ],
  },
  trips: {
    title: 'Trips',
    description: 'Manage route planning, assignments, and trip execution.',
    service: tripService,
    createLabel: 'Create Trip',
    searchPlaceholder: 'Search trips by code, source, destination, or driver...',
    searchableKeys: ['tripCode', 'vehicle', 'driver', 'source', 'destination', 'tripStatus'],
    summaryCards: [
      { title: 'Total Trips', value: trips.length, helper: 'Tracked routes' },
      { title: 'Planned', value: 1, helper: 'Awaiting dispatch' },
      { title: 'In Progress', value: 1, helper: 'Currently running' },
      { title: 'Completed', value: 1, helper: 'Closed trips' },
    ],
    columns: [
      { key: 'tripCode', label: 'Trip Code' },
      { key: 'vehicle', label: 'Vehicle' },
      { key: 'driver', label: 'Driver' },
      { key: 'source', label: 'Source' },
      { key: 'destination', label: 'Destination' },
      { key: 'plannedDistance', label: 'Planned Distance' },
      { key: 'actualDistance', label: 'Actual Distance' },
      { key: 'tripStatus', label: 'Status' },
    ],
    fields: [
      { name: 'tripCode', label: 'Trip Code' },
      { name: 'vehicle', label: 'Vehicle' },
      { name: 'driver', label: 'Driver' },
      { name: 'source', label: 'Source' },
      { name: 'destination', label: 'Destination' },
      { name: 'plannedDistance', label: 'Planned Distance', type: 'number' },
      { name: 'actualDistance', label: 'Actual Distance', type: 'number' },
      { name: 'tripStatus', label: 'Status', type: 'select', options: [
        { label: 'Planned', value: 'PLANNED' },
        { label: 'In Progress', value: 'IN_PROGRESS' },
        { label: 'Completed', value: 'COMPLETED' },
        { label: 'Cancelled', value: 'CANCELLED' },
      ] },
    ],
  },
  maintenance: {
    title: 'Maintenance',
    description: 'Track vehicle maintenance requests, approvals, and completion status.',
    service: maintenanceService,
    createLabel: 'Create Request',
    searchPlaceholder: 'Search maintenance requests...',
    searchableKeys: ['maintenanceCode', 'vehicle', 'issueTitle', 'priority', 'maintenanceStatus'],
    summaryCards: [
      { title: 'Requests', value: maintenanceRequests.length, helper: 'Open and closed' },
      { title: 'Pending', value: 1, helper: 'Awaiting approval' },
      { title: 'Approved', value: 1, helper: 'Ready for work' },
      { title: 'Critical', value: 0, helper: 'High urgency' },
    ],
    columns: [
      { key: 'maintenanceCode', label: 'Request Code' },
      { key: 'vehicle', label: 'Vehicle' },
      { key: 'issueTitle', label: 'Issue' },
      { key: 'priority', label: 'Priority' },
      { key: 'maintenanceStatus', label: 'Status' },
    ],
    fields: [
      { name: 'maintenanceCode', label: 'Request Code' },
      { name: 'vehicle', label: 'Vehicle' },
      { name: 'issueTitle', label: 'Issue Title' },
      { name: 'description', label: 'Description', type: 'textarea', span: 2 },
      { name: 'priority', label: 'Priority', type: 'select', options: [
        { label: 'Low', value: 'LOW' },
        { label: 'Medium', value: 'MEDIUM' },
        { label: 'High', value: 'HIGH' },
        { label: 'Critical', value: 'CRITICAL' },
      ] },
      { name: 'maintenanceStatus', label: 'Status', type: 'select', options: [
        { label: 'Pending', value: 'PENDING' },
        { label: 'Approved', value: 'APPROVED' },
        { label: 'In Progress', value: 'IN_PROGRESS' },
        { label: 'Completed', value: 'COMPLETED' },
        { label: 'Rejected', value: 'REJECTED' },
      ] },
    ],
  },
  fuelLogs: {
    title: 'Fuel Logs',
    description: 'Record fueling activity, vehicle odometer readings, and related costs.',
    service: fuelService,
    createLabel: 'Add Fuel Entry',
    searchPlaceholder: 'Search fuel logs...',
    searchableKeys: ['fuelCode', 'trip', 'vehicle', 'fuelStation', 'fuelType'],
    summaryCards: [
      { title: 'Fuel Logs', value: fuelLogs.length, helper: 'Recorded refuels' },
      { title: 'Diesel', value: 2, helper: 'Common fuel type' },
      { title: 'EV', value: 0, helper: 'Electric fleet' },
      { title: 'Avg Cost', value: '$134K', helper: 'Per refuel sample' },
    ],
    columns: [
      { key: 'fuelCode', label: 'Fuel Code' },
      { key: 'fuelStation', label: 'Station' },
      { key: 'fuelType', label: 'Fuel Type' },
      { key: 'liters', label: 'Liters' },
      { key: 'cost', label: 'Cost' },
      { key: 'odometerReading', label: 'Odometer' },
      { key: 'fuelDate', label: 'Date' },
    ],
    fields: [
      { name: 'fuelCode', label: 'Fuel Code' },
      { name: 'trip', label: 'Trip' },
      { name: 'vehicle', label: 'Vehicle' },
      { name: 'fuelStation', label: 'Fuel Station' },
      { name: 'fuelType', label: 'Fuel Type', type: 'select', options: [
        { label: 'Petrol', value: 'PETROL' },
        { label: 'Diesel', value: 'DIESEL' },
        { label: 'CNG', value: 'CNG' },
        { label: 'EV', value: 'EV' },
      ] },
      { name: 'liters', label: 'Liters', type: 'number' },
      { name: 'cost', label: 'Cost', type: 'number' },
      { name: 'odometerReading', label: 'Odometer Reading', type: 'number' },
      { name: 'fuelDate', label: 'Date', type: 'date' },
    ],
  },
  expenses: {
    title: 'Expenses',
    description: 'Capture operational expenses tied to trips and vehicles.',
    service: expenseService,
    createLabel: 'Add Expense',
    searchPlaceholder: 'Search expenses...',
    searchableKeys: ['expenseCode', 'expenseType', 'trip', 'vehicle', 'description'],
    summaryCards: [
      { title: 'Expenses', value: expenses.length, helper: 'Logged records' },
      { title: 'Fuel', value: 1, helper: 'Expense mix' },
      { title: 'Toll', value: 1, helper: 'Road charges' },
      { title: 'Total', value: '$166.8K', helper: 'Sample total' },
    ],
    columns: [
      { key: 'expenseCode', label: 'Expense Code' },
      { key: 'expenseType', label: 'Type' },
      { key: 'trip', label: 'Trip' },
      { key: 'vehicle', label: 'Vehicle' },
      { key: 'amount', label: 'Amount' },
      { key: 'description', label: 'Description' },
    ],
    fields: [
      { name: 'expenseCode', label: 'Expense Code' },
      { name: 'trip', label: 'Trip' },
      { name: 'vehicle', label: 'Vehicle' },
      { name: 'expenseType', label: 'Expense Type', type: 'select', options: [
        { label: 'Fuel', value: 'Fuel' },
        { label: 'Toll', value: 'Toll' },
        { label: 'Parking', value: 'Parking' },
        { label: 'Repair', value: 'Repair' },
        { label: 'Food', value: 'Food' },
        { label: 'Other', value: 'Other' },
      ] },
      { name: 'amount', label: 'Amount', type: 'number' },
      { name: 'description', label: 'Description', type: 'textarea', span: 2 },
    ],
  },
};